[project]
name = "amld2025"
version = "0.1.0"
description = "Workshop: Leveraging Large Language Models for Intelligent Claim Handling: A Hands-On Industry Case Study"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
